// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#ifndef CXX___XML_XSD_PROFILE_PIMPL_H
#define CXX___XML_XSD_PROFILE_PIMPL_H

#include "profile-pskel.h"

namespace profile
{
  class profile_pimpl: public profile_pskel
  {
    public:
    virtual void
    pre ();

    virtual void
    filename (const ::std::string&);

    virtual void
    type (const ::std::string&);

    virtual void
    post_profile ();
  };
}

#endif // CXX___XML_XSD_PROFILE_PIMPL_H
