// Not copyrighted - public domain.
//
// This sample parser implementation was generated by CodeSynthesis XSD,
// an XML Schema to C++ data binding compiler. You may use it in your
// programs without any restrictions.
//

#include "profile-pimpl.h"

namespace profile
{
  // profile_pimpl
  //

  void profile_pimpl::
  pre ()
  {
  }

  void profile_pimpl::
  filename (const ::std::string& filename)
  {
    // TODO
    //
  }

  void profile_pimpl::
  type (const ::std::string& type)
  {
    // TODO
    //
  }

  void profile_pimpl::
  post_profile ()
  {
  }
}

